In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
import matplotlib.pyplot as plt


In [4]:
np.random.seed(40)
data = np.random.randint(100,200, size =200)
data

array([170, 191, 107, 137, 156, 150, 165, 112, 171, 119, 131, 174, 155,
       183, 159, 191, 173, 196, 149, 153, 173, 108, 152, 130, 179, 114,
       192, 158, 174, 122, 103, 191, 199, 171, 155, 183, 128, 113, 137,
       182, 150, 179, 167, 130, 160, 144, 146, 187, 143, 135, 198, 131,
       182, 105, 180, 165, 107, 192, 141, 199, 195, 188, 193, 125, 183,
       158, 198, 170, 157, 157, 183, 185, 136, 163, 174, 188, 100, 101,
       133, 152, 172, 157, 134, 114, 178, 171, 156, 177, 186, 184, 182,
       191, 112, 190, 173, 127, 100, 121, 194, 132, 151, 150, 120, 141,
       178, 155, 147, 143, 191, 176, 129, 145, 107, 110, 161, 119, 168,
       125, 161, 198, 116, 188, 161, 151, 188, 141, 158, 121, 131, 195,
       143, 168, 116, 103, 115, 179, 104, 106, 194, 166, 185, 151, 190,
       183, 102, 109, 106, 139, 125, 156, 117, 113, 107, 150, 196, 148,
       153, 100, 138, 160, 148, 167, 197, 161, 145, 161, 110, 177, 157,
       152, 140, 101, 152, 158, 188, 122, 148, 124, 158, 193, 17

In [5]:
#prepare input sequences (x = past 7 days)
#labels y = next day
def prepare_data(data, sequence_length = 7):
    x, y = [], []
    for i in range(len(data) - sequence_length):
        x.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length])
    return np.array(x), np.array(y)

In [6]:
X, y = prepare_data(data)


In [7]:
X

array([[170, 191, 107, ..., 156, 150, 165],
       [191, 107, 137, ..., 150, 165, 112],
       [107, 137, 156, ..., 165, 112, 171],
       ...,
       [196, 102, 164, ..., 179, 194, 110],
       [102, 164, 175, ..., 194, 110, 115],
       [164, 175, 179, ..., 110, 115, 197]])

In [8]:
y

array([112, 171, 119, 131, 174, 155, 183, 159, 191, 173, 196, 149, 153,
       173, 108, 152, 130, 179, 114, 192, 158, 174, 122, 103, 191, 199,
       171, 155, 183, 128, 113, 137, 182, 150, 179, 167, 130, 160, 144,
       146, 187, 143, 135, 198, 131, 182, 105, 180, 165, 107, 192, 141,
       199, 195, 188, 193, 125, 183, 158, 198, 170, 157, 157, 183, 185,
       136, 163, 174, 188, 100, 101, 133, 152, 172, 157, 134, 114, 178,
       171, 156, 177, 186, 184, 182, 191, 112, 190, 173, 127, 100, 121,
       194, 132, 151, 150, 120, 141, 178, 155, 147, 143, 191, 176, 129,
       145, 107, 110, 161, 119, 168, 125, 161, 198, 116, 188, 161, 151,
       188, 141, 158, 121, 131, 195, 143, 168, 116, 103, 115, 179, 104,
       106, 194, 166, 185, 151, 190, 183, 102, 109, 106, 139, 125, 156,
       117, 113, 107, 150, 196, 148, 153, 100, 138, 160, 148, 167, 197,
       161, 145, 161, 110, 177, 157, 152, 140, 101, 152, 158, 188, 122,
       148, 124, 158, 193, 174, 189, 196, 143, 164, 171, 106, 14

In [9]:
X = X.reshape((X.shape[0], X.shape[1], 1))  # Reshape for RNN input
X.shape

(193, 7, 1)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
#build the RNN model
rnnmodel = Sequential()
rnnmodel.add(SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], 1)))
rnnmodel.add(Dense(1))  # Output layer for regression

rnnmodel.compile(optimizer='adam', loss='mse')
#train the model
history = rnnmodel.fit(X_train, y_train, epochs=30, verbose=1)

Epoch 1/30
5/5 [==============================] - 1s 3ms/step - loss: 20499.2930
Epoch 2/30
5/5 [==============================] - 0s 3ms/step - loss: 14510.7471
Epoch 3/30
5/5 [==============================] - 0s 3ms/step - loss: 9613.1982
Epoch 4/30
5/5 [==============================] - 0s 3ms/step - loss: 5404.5825
Epoch 5/30
5/5 [==============================] - 0s 3ms/step - loss: 2191.0659
Epoch 6/30
5/5 [==============================] - 0s 3ms/step - loss: 1052.5356
Epoch 7/30
5/5 [==============================] - 0s 3ms/step - loss: 1703.2356
Epoch 8/30
5/5 [==============================] - 0s 3ms/step - loss: 1220.2599
Epoch 9/30
5/5 [==============================] - 0s 3ms/step - loss: 1121.3513
Epoch 10/30
5/5 [==============================] - 0s 2ms/step - loss: 1171.2767
Epoch 11/30
5/5 [==============================] - 0s 3ms/step - loss: 1081.5742
Epoch 12/30
5/5 [==============================] - 0s 3ms/step - loss: 1030.2242
Epoch 13/30
5/5 [==================

In [12]:
y_pred  = rnnmodel.predict(X_test)


2/2 [==============================] - 0s 4ms/step


In [13]:
X_test.shape

(39, 7, 1)

In [15]:
# Convert set to sorted list, then to numpy array and reshape for RNN input
new_data = np.array(sorted([101, 112, 113, 154, 167, 181, 106])).reshape((1, 7, 1))


In [16]:
new_prediction = rnnmodel.predict(new_data.reshape(1, 7, 1))
print("Predicted value:", new_prediction[0][0])

1/1 [==============================] - 0s 24ms/step
Predicted value: 145.22757


In [17]:
X_test[1]

array([[106],
       [194],
       [166],
       [185],
       [151],
       [190],
       [183]])

In [18]:
y_test[1]

102

In [19]:
rnnmodel.predict(X_test[1].reshape(1, 7, 1))

1/1 [==============================] - 0s 25ms/step


array([[166.69818]], dtype=float32)